name: Deploy to cPanel
on:
  push:
    branches: [main, master]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create Laravel .env
        working-directory: ./api
        run: |
          cat > .env << EOF
          APP_NAME=${{ secrets.LARAVEL_APP_NAME }}
          APP_ENV=production
          APP_KEY=${{ secrets.LARAVEL_APP_KEY }}
          APP_DEBUG=false
          APP_URL=https://feca4development.org/backend

          # Database Configuration
          DB_CONNECTION=mysql
          DB_HOST=${{ secrets.DB_HOST }}
          DB_PORT=${{ secrets.DB_PORT }}
          DB_DATABASE=${{ secrets.DB_DATABASE }}
          DB_USERNAME=${{ secrets.DB_USERNAME }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}

          # Session Configuration (disabled for API)
          SESSION_DRIVER=array
          SESSION_LIFETIME=120
          SESSION_ENCRYPT=false

          # Cache Configuration
          CACHE_DRIVER=file
          QUEUE_CONNECTION=sync

          # JWT Configuration
          JWT_PUBLIC_KEY="${{ secrets.JWT_PUBLIC_KEY }}"
          JWT_PRIVATE_KEY="${{ secrets.JWT_PRIVATE_KEY }}"

          # Admin Configuration
          ADMIN_EMAIL=${{ secrets.ADMIN_EMAIL }}
          ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }}
          EOF

      - name: Create root .htaccess for security
        run: |
          cat > .htaccess << EOF
          # Prevent directory browsing
          Options -Indexes

          # Deny access to sensitive files and directories
          <FilesMatch "\.(env|git|gitignore|gitattributes)$">
              Require all denied
          </FilesMatch>

          <DirectoryMatch "\.git">
              Require all denied
          </DirectoryMatch>

          # Hide backend directory from direct access
          <DirectoryMatch "backend">
              Require all denied
          </DirectoryMatch>

          # Block access to composer files
          <FilesMatch "(composer\.(json|lock)|package\.(json|lock))$">
              Require all denied
          </FilesMatch>

          # Block access to log files
          <FilesMatch "\.log$">
              Require all denied
          </FilesMatch>
          EOF

      - name: Create API .htaccess for Laravel routing
        run: |
          cat > api_htaccess << EOF
          # Laravel API routing
          <IfModule mod_rewrite.c>
              RewriteEngine On
              
              # Handle Authorization Header for API authentication
              RewriteCond %{HTTP:Authorization} .
              RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
              
              # Handle preflight OPTIONS requests for CORS
              RewriteCond %{REQUEST_METHOD} OPTIONS
              RewriteRule ^(.*)$ \$1 [R=200,L]
              
              # Redirect Trailing Slashes If Not A Folder...
              RewriteCond %{REQUEST_FILENAME} !-d
              RewriteCond %{REQUEST_URI} (.+)/$
              RewriteRule ^ %1 [L,R=301]
              
              # Send ALL requests to index.php in api directory
              RewriteCond %{REQUEST_FILENAME} !-d
              RewriteCond %{REQUEST_FILENAME} !-f
              RewriteRule ^(.*)$ index.php [QSA,L]
          </IfModule>

          # CORS and API headers
          <IfModule mod_headers.c>
              # CORS headers for API
              Header always set Access-Control-Allow-Origin "*"
              Header always set Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS, PATCH"
              Header always set Access-Control-Allow-Headers "Origin, X-Requested-With, Content-Type, Accept, Authorization, X-CSRF-TOKEN"
              Header always set Access-Control-Max-Age "3600"
              
              # Security headers
              Header always set X-Content-Type-Options nosniff
              Header always set X-Frame-Options SAMEORIGIN
              Header always set X-XSS-Protection "1; mode=block"
              Header always set Referrer-Policy "strict-origin-when-cross-origin"
          </IfModule>

          # Allow all access to this directory (API endpoints)
          <RequireAll>
              Require all granted
          </RequireAll>

          # Prevent directory browsing
          Options -Indexes

          # Deny access to sensitive files only
          <FilesMatch "\.(env|git|gitignore|gitattributes|log)$">
              Order allow,deny
              Deny from all
          </FilesMatch>

          # Deny access to .git directories
          <DirectoryMatch "\.git">
              Order allow,deny
              Deny from all
          </DirectoryMatch>
          EOF

      - name: Create deployment package
        run: |
          mkdir deploy

          # Copy Laravel API code (exclude vendor for composer install via SSH)
          rsync -av \
            --exclude=vendor \
            --exclude=node_modules \
            --exclude=.git \
            --exclude=.gitignore \
            --exclude=.gitattributes \
            --exclude=storage/logs/* \
            --exclude=bootstrap/cache/* \
            ./api/ deploy/

          # Move the API .htaccess to the deploy directory
          mv api_htaccess deploy/.htaccess

          # Copy root .htaccess for additional security
          cp .htaccess deploy/root.htaccess

      - name: Deploy via SFTP
        run: |
          sshpass -p "${{ secrets.CPANEL_PASSWORD }}" sftp -o StrictHostKeyChecking=no -P ${{ secrets.CPANEL_PORT }} ${{ secrets.CPANEL_USERNAME }}@${{ secrets.CPANEL_HOST }} <<EOF
          cd public_html

          # Remove old directories (both api and backend for clean deployment)
          rm -rf api backend

          # Upload new files to backend directory
          lcd deploy
          mkdir backend
          put -r * backend/

          # Move root htaccess to document root for additional security
          get backend/root.htaccess .htaccess
          rm backend/root.htaccess

          quit
          EOF

      - name: Setup Laravel on server via SSH
        run: |
          sshpass -p "${{ secrets.CPANEL_PASSWORD }}" ssh -o StrictHostKeyChecking=no -p ${{ secrets.CPANEL_PORT }} ${{ secrets.CPANEL_USERNAME }}@${{ secrets.CPANEL_HOST }} << 'ENDSSH'
          cd public_html/backend

          # Check PHP version
          echo "Checking PHP version..."
          php -v

          # Install composer dependencies
          echo "Installing Composer dependencies..."
          composer install --no-dev --optimize-autoloader --no-interaction

          # Set proper permissions
          chmod -R 755 storage bootstrap/cache
          chmod -R 775 storage/logs storage/framework

          # Clear and cache configurations
          php artisan config:clear
          php artisan cache:clear
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

          # Create storage link if needed
          php artisan storage:link || true

          echo "Laravel API deployment completed successfully"
          ENDSSH
